import { Roboto } from "next/font/google";
import "./globals.css";
import Headrer from "./_components/Headrer";
import Footer from "./_components/Footer";
import "@fortawesome/fontawesome-free/css/all.min.css";
import { ClerkProvider } from "@clerk/nextjs";
import CartContext from "./_Context/CartContext";

const inter = Roboto({ subsets: ["latin"], weight: "500" });

export const metadata = {
  title: "Lamp Store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <CartContext>
        <html lang="en">
          <body className={inter.className}>
            <Headrer />
            {children}
            <Footer />
          </body>
        </html>
      </CartContext>
    </ClerkProvider>
  );
}
